### PR TITLE
Run tests on Go 1.21

### LINKED ISSUE #405: TestBrokenTLS_ClientHasExpiredCert fail with golang-1.21
Building grpcurl 1.8.7 with golang-1.21 for Fedora Rawhide fails in the following test:

~~~
--- FAIL: TestBrokenTLS_ClientHasExpiredCert (0.01s)
    tls_settings_test.go:217: expecting TLS certificate error, got: remote error: tls: expired certificate
~~~

### PR DESCRIPTION
**Pull request by sigv**
For the most part, there are no breaking changes.

However, the expired certificate is now showing "expired certificate" although previously it showed a simpler "bad certificate" which was hard-coded into the TLS settings test scenario.

Closes #405.

### CODE REVIEW

File: tls_settings_test.go [hunk 1]
```diff
@@ -213,7 +213,10 @@ func TestBrokenTLS_ClientHasExpiredCert(t *testing.T) {
 		e.Close()
 		t.Fatal("expecting TLS failure setting up server and client")
 	}
-	if !strings.Contains(err.Error(), "bad certificate") {
+	// Go 1.21 uses "expired certificate" in the error message.
+	// Older Go versions use a simpler "bad certificate".
+	// `runtime.Version()` exists, but we don't want to parse a version String for comparison.
+	if !strings.Contains(err.Error(), "expired certificate") && !strings.Contains(err.Error(), "bad certificate") {
```
Comment (dragonsinth) [inline tls_settings_test.go:219]:
```suggestion
	if !strings.Contains(err.Error(), "certificate") {
```

**Comment by dragonsinth** [comment]
https://github.com/fullstorydev/grpcurl/issues/405

File: tls_settings_test.go (hunk 1 above)
Comment (sigv) [reply tls_settings_test.go]: Thanks for the simplification!
The suggestion has been applied.

**Review by dragonsinth — APPROVED** [review]
